<!DOCTYPE html>
<html>

<head>

    <title>Cavaleiro</title>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="css/estilos.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

</head>

<body>

    <div id="area-cabecalho">

        <div id="area-logo">
            <h1>Cavaleiro<span class="branco">Game</span></h1>
        </div>
        <div id="area-menu">
            <a href="/">Home</a>
            <a href="tutorial">Tutorial</a>
            <a href="login">Login</a>
            <a href="cadastro">Cadastro</a>
            <a href="login">Novo Post</a>
            
        </div>
    </div>

    <div class="flex-box">

        <div id="area-postagens">

        <div class="alert alert-success" role="alert">
           Cadastro Realizado com Sucesso     
        </div>
            
        
        <a class="btn btn-success" href="/login" role="button">Realizar Login</a>

        </div>

        
    </div>

    <div id="area-rodape">
        Todos os direitos Reservados
    </div>

</body>



</html>