<!DOCTYPE html>
<html>

<head>

    <title>Cavaleiro</title>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="css/estilos.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

</head>

<body>

    <div id="area-cabecalho">

        <div id="area-logo">
            <h1>Cavaleiro<span class="branco">Game</span></h1>
        </div>
        <div id="area-menu">
        <a href="/">Home</a>
            <a href="download">Baixar</a>
            <a href="tutorial">Tutorial</a>
            <a href="login">Login</a>
            <a href="login">Novo Post</a>
            
        </div>
    </div>

    <div class="flex-box">

        <div class="container" style="width: 60%; padding-bottom: 30px;">

            <form action="/registrar" method="POST">
               
                  
                <h4>Cadastro</h4>
                <div class="form-group">
                    <input type="text" class="form-control" name="nome" placeholder="nome *">
                    <input type="text" class="form-control" name="email" placeholder="E-mail *">
                    <input type="password" class="form-control" name="senha" placeholder="Senha *">
                    <input type="text" class="form-control" name="cod" placeholder="Código">
                </div>
                
                
                <p><input class="btn btn-outline-success" type="submit" value="Criar uma Conta" /></p>

                <?php if($this->view->erroCadastro) { ?>
                    <div class="alert alert-danger" role="alert">
                       *Erro ao tentar realizar o cadastro, verifique se os campos foram preenchidos corretamente
                    </div>
                <?php } ?>

            </form>
        </div>
    </div>

    <div id="area-rodape">
        Todos os direitos Reservados
    </div>

</body>



</html>