<!DOCTYPE html>
<html>

<head>

    <title>Cavaleiro</title>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="css/estilos.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

</head>

<body>

    <div id="area-cabecalho">

        <div id="area-logo">
            <h1>Cavaleiro<span class="branco">Game</span></h1>
        </div>
        <div id="area-menu">
            <a href="/">Home</a>
            <a href="tutorial">Tutorial</a>
            <a href="login">Login</a>
            <a href="cadastro">Cadastro</a>
            <a href="login">Novo Post</a>
            
        </div>
    </div>

    <div class="flex-box">

        <div id="area-postagens">

            <div class="card mb-3">
                <img src="https://gamehall.com.br/wp-content/uploads/2018/07/Top-10-Western-Destaque.jpg" class="card-img-top" alt="...">
                <div class="card-body">
                 <h5 class="card-titulo">Baixar o Jogo</h5>
                  <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sagittis id magna sit amet malesuada. Nulla semper neque diam, ac fringilla magna pellentesque sed. Nam id lacus hendrerit, ultricies orci nec, pulvinar ex. Vivamus vestibulum enim sed justo dignissim, nec vehicula urna fringilla. Donec ultricies pulvinar vestibulum. Vestibulum facilisis odio at consequat venenatis. Cras tristique, elit suscipit facilisis fringilla, lectus libero vulputate enim, in tempus neque turpis in magna. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus vel turpis felis. In nec pellentesque mi. Nullam id porta eros, sodales ornare elit. Nullam dictum augue aliquam, rutrum lectus eget, blandit magna. Vivamus sit amet lacus aliquam, rhoncus nisi non, rutrum velit. Aliquam bibendum augue ut nunc placerat sollicitudin. Donec non auctor enim. Fusce accumsan elementum auctor.

                    Sed et quam vitae lacus imperdiet fermentum et id ipsum. In egestas purus sem, egestas ultricies augue pellentesque eget. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris eget nisl sollicitudin, blandit mi sed, sodales justo. Vestibulum vulputate massa eros. Morbi pretium, metus at posuere sodales, odio mauris congue diam, sit amet luctus ante nibh quis diam. Duis efficitur ipsum nec nisi dapibus tempor. Pellentesque ac venenatis erat. Suspendisse feugiat leo leo, non ultrices neque consequat a. Integer vitae mauris diam. Sed at hendrerit enim.
                    
                    Ut aliquam sapien id neque sollicitudin, eget ultrices arcu ullamcorper. Vivamus eleifend massa purus, ac condimentum turpis pharetra in. In interdum eu augue non facilisis. Fusce placerat rhoncus accumsan. Vivamus sed ex volutpat, lobortis ex vel, tempus lacus. Vivamus aliquam fermentum metus, eget auctor ipsum condimentum iaculis. Integer in massa et sapien lacinia vehicula. Fusce in efficitur felis. Integer luctus, lectus sit amet iaculis maximus, mauris purus faucibus mi, vitae tristique neque tortor gravida quam. Proin vulputate mauris magna, nec facilisis ex fermentum sed. Nullam mattis erat et nisi faucibus, at facilisis massa gravida. Aenean sit amet elit in purus tristique auctor. Aenean augue nisl, blandit id vehicula vitae, venenatis a tortor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.
                    
                    Curabitur maximus mauris vel eleifend lobortis. Nullam lacinia tortor et elit aliquam, ut lobortis urna tempor. Nam id fringilla quam, a vehicula ante. Mauris fringilla egestas felis non pulvinar. Cras vitae facilisis purus. Donec blandit ut tellus ut aliquet. Praesent sed vehicula dolor. Integer ullamcorper tortor ligula. Phasellus vitae libero elit. Nunc sollicitudin nisl dignissim scelerisque faucibus. Nam non pulvinar justo. Nulla non laoreet dolor, sed molestie justo.
                    
                    Nunc facilisis ex a neque pretium accumsan. Ut elementum congue lobortis. Vestibulum quam felis, finibus sed gravida in, congue vitae magna. Nulla facilisi. Nunc pellentesque, est nec placerat convallis, felis mauris commodo urna, mollis ultrices mauris augue eu purus. Vestibulum pellentesque enim vitae dolor ornare, ut congue augue aliquet. Integer mollis feugiat massa ut ultrices. Mauris sit amet orci in felis imperdiet eleifend. Suspendisse venenatis dui et tortor condimentum efficitur. Morbi malesuada commodo dui quis accumsan. Integer fringilla mauris nisl, in malesuada ante dapibus nec. Fusce condimentum purus nec vulputate facilisis. Pellentesque consequat ligula vel nisl iaculis, auctor vulputate ex laoreet. Fusce ut lectus sit amet mi bibendum pulvinar eget sit amet massa. Ut leo augue, volutpat vel tristique id, elementum eu mi.</p>
                  
                </div>
              </div>

        </div>

        
    </div>

    <div id="area-rodape">
        Todos os direitos Reservados
    </div>

</body>



</html>