<!DOCTYPE html>
<html>

<head>

    <title>Cavaleiro</title>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="css/estilos.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

</head>

<body>

    <div id="area-cabecalho">

        <div id="area-logo">
            <h1>Cavaleiro<span class="branco">Game</span></h1>
        </div>
        <div id="area-menu">
            <a href="/">Home</a>
            <a href="download">Baixar</a>
            <a href="tutorial">Tutorial</a>
            <a href="cadastro">Cadastro</a>
            <a href="login">Novo Post</a>
        </div>
    </div>

    <div class="flex-box">

        <form class="form-inline" method="POST" action="/autenticar">
            <div class="form-group mb-2">
              <label for="staticEmail2" class="sr-only">Email</label>
              <input type="text" class="form-control" id="inputPassword2" placeholder="samuel.silva@uni9.edu.br" name="email">
            </div>
            <div class="form-group mx-sm-3 mb-2">
              <label for="inputPassword2" class="sr-only">Password</label>
              <input type="password" class="form-control" id="inputPassword2" placeholder="Password" name="senha">
            </div>

            <button type="submit" class="btn btn-outline-success">Entrar</button>

            <?php if ($this->view->loginEr == 'erro') { ?>
          
            <div class = "row">
                <div class="col">

                    <div class="alert alert-danger" role="alert">
                        *E-mail ou senha inválidos
                    </div>
                   
                </div>
            </div>
            
            <?php } ?>
            
          </form>
    </div>

    <div id="area-rodape">
        Todos os direitos Reservados
    </div>

</body>



</html>